services:
  gateway:
    image: gateway
    build:
      context: .
      dockerfile: src/Gateway/Gateway/Dockerfile

  menu.api:
    image: menu.api
    build:
      context: .
      dockerfile: src/Menu/Menu.Api/Dockerfile

  menu.worker:
    image: menu.worker
    build:
      context: .
      dockerfile: src/Menu/Menu.Worker/Dockerfile
