/*
 * Menu.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using Menu.Client.Client;
using Menu.Client.Api;
// uncomment below to import models
//using Menu.Client.Model;

namespace Menu.Client.Test.Api
{
    /// <summary>
    ///  Class for testing MenuApiApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class MenuApiApiTests : IDisposable
    {
        private MenuApiApi instance;

        public MenuApiApiTests()
        {
            instance = new MenuApiApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MenuApiApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' MenuApiApi
            //Assert.IsType<MenuApiApi>(instance);
        }

        /// <summary>
        /// Test GetMenuAllItems
        /// </summary>
        [Fact]
        public void GetMenuAllItemsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetMenuAllItems();
            //Assert.IsType<List<MenuItem>>(response);
        }
    }
}
