/*
 * Gateway
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using Gateway.ApiClient.Client;
using Gateway.ApiClient.Api;
// uncomment below to import models
//using Gateway.ApiClient.Model;

namespace Gateway.ApiClient.Test.Api
{
    /// <summary>
    ///  Class for testing GatewayApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class GatewayApiTests : IDisposable
    {
        private GatewayApi instance;

        public GatewayApiTests()
        {
            instance = new GatewayApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GatewayApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' GatewayApi
            //Assert.IsType<GatewayApi>(instance);
        }

        /// <summary>
        /// Test CreatMenuItem
        /// </summary>
        [Fact]
        public void CreatMenuItemTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int id = null;
            //CreateMenuItemRequest createMenuItemRequest = null;
            //instance.CreatMenuItem(id, createMenuItemRequest);
        }

        /// <summary>
        /// Test GetAlleMenuItems
        /// </summary>
        [Fact]
        public void GetAlleMenuItemsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetAlleMenuItems();
            //Assert.IsType<List<MenuItem>>(response);
        }
    }
}
