/*
 * Gateway
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Gateway.ApiClient.Model;
using Gateway.ApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Gateway.ApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing CreateMenuItemRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateMenuItemRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreateMenuItemRequest
        //private CreateMenuItemRequest instance;

        public CreateMenuItemRequestTests()
        {
            // TODO uncomment below to create an instance of CreateMenuItemRequest
            //instance = new CreateMenuItemRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreateMenuItemRequest
        /// </summary>
        [Fact]
        public void CreateMenuItemRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreateMenuItemRequest
            //Assert.IsType<CreateMenuItemRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Price'
        /// </summary>
        [Fact]
        public void PriceTest()
        {
            // TODO unit test for the property 'Price'
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
    }
}
