/*
 * Gateway
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Gateway.ApiClient.Model;
using Gateway.ApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Gateway.ApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing MenuItem
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MenuItemTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MenuItem
        //private MenuItem instance;

        public MenuItemTests()
        {
            // TODO uncomment below to create an instance of MenuItem
            //instance = new MenuItem();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MenuItem
        /// </summary>
        [Fact]
        public void MenuItemInstanceTest()
        {
            // TODO uncomment below to test "IsType" MenuItem
            //Assert.IsType<MenuItem>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Price'
        /// </summary>
        [Fact]
        public void PriceTest()
        {
            // TODO unit test for the property 'Price'
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
    }
}
